spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/eventa?connectionTimeZone=Europe/Belgrade}
spring.datasource.username=${DB_USER:eventa}
spring.datasource.password=${DB_PASSWORD}
app.seed=${APP_SEED:false}
